
//auth.js
export const SHOW_LOGIN_MODEL = 'SHOW_LOGIN_MODEL'
export const HIDE_LOGIN_MODEL = 'HIDE_LOGIN_MODEL'
export const SET_TOKEN = 'SET_TOKEN'
export const SET_ID = 'SET_ID'
export const SET_NAME = 'SET_NAME'
export const SET_EMAIL = 'SET_EMAIL'
export const SET_ROLE = 'SET_ROLE'
export const SET_PERMISSIONS = 'SET_PERMISSIONS'
export const SET_LOGIN_STATE = 'SET_LOGIN_STATE'
export const SET_EMAIL_VERIFIED_STATUS = 'SET_EMAIL_VERIFIED_STATUS'
export const SET_VERIFY_EMAIL_STATUS = 'SET_VERIFY_EMAIL_STATUS'
export const SET_LISTED_STATUS = 'SET_LISTED_STATUS'
export const LOGOUT = 'LOGOUT'
export const SET_ALIYUN_OSS = 'SET_ALIYUN_OSS'

//search.js
export const SET_SEARCH_USSTATE = 'SET_SEARCH_USSTATE'
export const SET_SEARCH_ADDRESS = 'SET_SEARCH_ADDRESS'
export const SET_SEARCH_COORDINATE = 'SET_SEARCH_COORDINATE'
export const SET_SEARCH_CATEGORIES = 'SET_SEARCH_CATEGORIES'
export const SET_SEARCH_COMPANY_NAME = 'SET_SEARCH_COMPANY_NAME'
export const SET_SEARCH_RESULTS = 'SET_SEARCH_RESULTS'
export const SET_SEARCH_PAGINATION = 'SET_SEARCH_PAGINATION'

//list.js
export const SET_LIST_LISTINFO = 'SET_LIST_LISTINFO'
export const SET_LIST_CALENDAR = 'SET_LIST_CALENDAR'
export const SET_LIST_PREVIOUS_APPOINTMENT = 'SET_LIST_PREVIOUS_APPOINTMENT'
export const SHOW_LIST_APPOINTMENT_TOOL = 'SHOW_APPOINTMENT_TOOL'
export const HIDE_LIST_APPOINTMENT_TOOL = 'HIDE_APPOINTMENT_TOOL'
export const SET_LIST_TAB = 'SET_LIST_TAB'
export const SET_LIST_CALENDAR_CONTROL = 'SET_LIST_CALENDAR_CONTROL'
export const SET_LIST_CALENDAR_SCHEDULE = 'SET_LIST_CALENDAR_SCHEDULE'

//dashboard.js
export const SET_DASHBOARD_USERINFO = 'SET_DASHBOARD_USERINFO'
export const SET_DASHBOARD_LISTINFO = 'SET_DASHBOARD_LISTINFO'
export const SET_DASHBOARD_APPOINTMENT = 'SET_DASHBOARD_APPOINTMENT'
export const START_EDIT_LISTINFO = 'START_EDIT_LISTINFO'
export const END_EDIT_LISTINFO = 'END_EDIT_LISTINFO'
export const GET_DASHBOARD_DATA = 'GET_DASHBOARD_DATA'

//clientbook.js
export const SET_CLIENTBOOK_CLIENTS = 'SET_CLIENTBOOK_CLIENTS'
export const SET_CLIENTBOOK_SELECTED_CLIENT = 'SET_CLIENTBOOK_SELECTED_CLIENT'
export const SET_CLIENTBOOK_ADDCLIENTBUTTON_STATUS = 'SET_CLIENTBOOK_ADDCLIENTBUTTON_STATUS'
export const SET_CLIENTBOOK_ADDAPPOINTMENTMODAL_STATUS = 'SET_CLIENTBOOK_ADDAPPOINTMENTMODAL_STATUS'
export const SET_CLIENTBOOK_NEWAPPOINTMENT = 'SET_CLIENTBOOK_NEWAPPOINTMENT'

//view.js
export const SET_VIEW_DRAWER_STATUS = 'SET_VIEW_DRAWER_STATUS'

//internal.js
export const INTERNAL_SET_PUBLIC_ADVISORS = 'INTERNAL_SET_PUBLIC_ADVISORS'
export const INTERNAL_SET_NEWPUBLICADVISORFORM_STATUS = 'INTERNAL_SET_NEWPUBLICADVISORFORM_STATUS'

//function.js
export const ENABLE_AGENTBOOK = 'ENABLE_AGENTBOOK'

//agentbook.js
export const UPDATE_AGENTS_LIST = 'UPDATE_AGENTS_LIST'
export const FETCH_AGENTS_SUCCESS = 'FETCH_AGENTS_SUCCESS'
export const FETCH_AGENTS_FAILURE = 'FETCH_AGENTS_FAILURE'
export const CREATE_AGENTS_SUCCESS = 'CREATE_AGENTS_SUCCESS'
export const CREATE_AGENTS_FAILURE = 'CREATE_AGENTS_FAILURE'
export const UPDATE_AGENTS_SUCCESS = 'UPDATE_AGENTS_SUCCESS'
export const UPDATE_AGENTS_FAILURE = 'UPDATE_AGENTS_FAILURE'
export const DELETE_AGENTS_SUCCESS = 'DELETE_AGENTS_SUCCESS'
export const DELETE_AGENTS_FAILURE = 'DELETE_AGENTS_FAILURE'
export const SET_AGENTBOOK_SELECTED_AGENT = 'SET_AGENTBOOK_SELECTED_AGENT'
