
export const INCREASE = 'INCREASE'
export const DECREASE = 'DECREASE'

//auth.js
export const SET_TOKEN = 'SET_TOKEN'
export const SET_ID = 'SET_ID'
export const SET_NAME = 'SET_NAME'
export const SET_EMAIL = 'SET_EMAIL'
export const SET_LOGIN_STATE = 'SET_LOGIN_STATE'
export const LOGOUT = 'LOGOUT'
//search.js
export const SET_SEARCH_USSTATE = 'SET_SEARCH_USSTATE'
export const SET_SEARCH_ADDRESS = 'SET_SEARCH_ADDRESS'
export const SET_SEARCH_COORDINATE = 'SET_SEARCH_COORDINATE'
export const SET_SEARCH_CATEGORIES = 'SET_SEARCH_CATEGORIES'
export const SET_SEARCH_COMPANY_NAME = 'SET_SEARCH_COMPANY_NAME'
